In [1]:
import pandas as pd

nonamp = pd.read_csv(
    "../raw/uniprotkb_reviewed_true_AND_length_5_TO_2026_06_03.tsv",
    sep="\t"
)

print(nonamp.shape)
print(nonamp.columns.tolist())

(16864, 7)
['Entry', 'Reviewed', 'Protein names', 'Gene Names', 'Organism', 'Length', 'Sequence']

In [2]:
print(nonamp.shape)
print(nonamp.columns.tolist())
nonamp.head()

(16864, 7)
['Entry', 'Reviewed', 'Protein names', 'Gene Names', 'Organism', 'Length', 'Sequence']

,Entry,Reviewed,Protein names,Gene Names,Organism,Length,Sequence
0,A0A068B6Q6,reviewed,Conotoxin Bt1.8,NaN,Conus betulinus (Beech cone),37,PDGRNAAAKAFDLITPTVRKGCCSNPACILNNPNQCG
1,A0A0B4J2F0,reviewed,Protein PIGBOS1 (PIGB opposite strand protein 1),PIGBOS1,Homo sapiens (Human),54,MFRRLTFAQLLFATVLGIAGGVYIFQPVFEQYAKDQKELKEKMQLV...
2,A0A0C5B5G6,reviewed,Mitochondrial-derived peptide MOTS-c (Mitochon...,MT-RNR1,Homo sapiens (Human),16,MRWQEMGYIFYPRKLR
3,A0A1B0GQX2,reviewed,Protein TUNAR (pTUNAR) (Beta cell and neural c...,Tunar,Mus musculus (Mouse),48,MVITSGNDEDRGGQEKESKEESVLAMLGIIGTILNLIVIIFVYIYTTL
4,A0A1Z0YU59,reviewed,Mambaquaretin-1 (MQ-1) (MQ1) (Upsilon-Da2a),NaN,Dendroaspis angusticeps (Eastern green mamba) ...,57,RPSFCNLPVKPGPCNGFFSAFYYSQKTNKCHSFTYGGCKGNANRFS...

In [3]:
print("Before:", nonamp.shape)

nonamp = nonamp.drop_duplicates(subset=["Sequence"])

print("After:", nonamp.shape)

Before: (16864, 7)
After: (12583, 7)

In [4]:
amp_df = pd.read_csv(
    "clean_amp_dataset.csv"
)

amp_sequences = set(amp_df["Sequence"])

overlap = nonamp[
    nonamp["Sequence"].isin(amp_sequences)
]

print("Overlap sequences:", len(overlap))

Overlap sequences: 277

In [5]:
import pandas as pd

amp_df = pd.read_csv(
    "clean_amp_dataset.csv"
)

amp_sequences = set(amp_df["Sequence"])

nonamp_clean = nonamp[
    ~nonamp["Sequence"].isin(amp_sequences)
].copy()

print("After overlap removal:", nonamp_clean.shape)

After overlap removal: (12306, 7)

In [6]:
print(nonamp_clean["Length"].describe())

count    12306.000000
mean        37.893142
std         16.193202
min          5.000000
25%         25.000000
50%         39.000000
75%         53.000000
max         60.000000
Name: Length, dtype: float64

In [7]:
nonamp_final = nonamp_clean.sample(
    n=8400,
    random_state=42
)

print(nonamp_final.shape)

(8400, 7)

In [8]:
nonamp_final.to_csv(
    "clean_nonamp_dataset.csv",
    index=False
)

print("Saved")

Saved

In [10]:
amp_df = pd.read_csv(
    "clean_amp_dataset.csv"
)

nonamp_df = pd.read_csv(
    "clean_nonamp_dataset.csv"
)

amp_final = pd.DataFrame({
    "Sequence": amp_df["Sequence"],
    "label": 1
})

nonamp_final = pd.DataFrame({
    "Sequence": nonamp_df["Sequence"],
    "label": 0
})

merged_df = pd.concat(
    [amp_final, nonamp_final],
    ignore_index=True
)

print(merged_df.shape)

print(
    merged_df["label"].value_counts()
)

(16800, 2)
label
1    8400
0    8400
Name: count, dtype: int64

In [11]:
merged_df = merged_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

merged_df.to_csv(
    "amp_nonamp_dataset.csv",
    index=False
)

print(merged_df.shape)

merged_df.head()

(16800, 2)

                          Sequence  label
0  ISGINASVVNIQKEIDRLNEVAKNLNESLIK      1
1                           WAIVLL      1
2                INVLGILGLLGKALSHL      1
3                           FPPWVL      1
4                AVTSSVADTTTVVRDDF      0